#!/usr/bin/env bash

set -euo pipefail

if [[ "${1:-""}" == "__init" ]]; then
  cat << EOF | "${0}"
git config --global user.name 'Cole Botkens'
git config --global user.email 'cole.mickens+colebot@gmail.com'
git remote update
EOF
  exit
elif [[ "${1-:""}" != "" ]] && [[ "${1-:""}" != ":" ]]; then
  nix-shell --pure \
    --keep GITHUB_ACTION \
    --keep CI_JOB_ID \
    --keep CACHIX_SIGNING_KEY_NIXPKGS_WAYLAND \
    --run "$(printf '\"%s\" ' "${@}")"
  exit
else
  #cat <(printf "set -x\n set -euo pipefail\n") /dev/stdin | \
  cat /dev/stdin | \
    nix-shell --pure \
      --keep CI_JOB_ID \
      --keep CACHIX_SIGNING_KEY_NIXPKGS_WAYLAND \
      --run "bash --noprofile --norc -eo pipefail </dev/stdin"
  exit
fi
